//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sperience
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDescription { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> SolutionTypeId { get; set; }
        public Nullable<int> MinimumSupplierMapping { get; set; }
        public bool Active { get; set; }
        public int LocationId { get; set; }
        public int CompanyId { get; set; }
        public int Createdby { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Deletedby { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> TempERPIdSG { get; set; }
        public Nullable<int> TempERPIdMY { get; set; }
    }
}
