//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sperience
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Id { get; set; }
        public int CurrencyId { get; set; }
        public string RegistrationId { get; set; }
        public string GSTRegistrationId { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int CountryId { get; set; }
        public string ZipCode { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public Nullable<int> GSTPercent { get; set; }
        public Nullable<int> SalesMarkupPercent { get; set; }
        public Nullable<decimal> RiskTolerance { get; set; }
        public Nullable<int> PageSize { get; set; }
        public string CurrencySymbol { get; set; }
        public string CompanyLogo { get; set; }
        public string TaxName { get; set; }
        public Nullable<int> ReceivablesAllowance { get; set; }
        public Nullable<int> IRQPurchaseCutoff { get; set; }
        public Nullable<decimal> MinimumSalesMargin { get; set; }
        public Nullable<decimal> FloorSalesMargin { get; set; }
        public Nullable<decimal> MinimumCostSavings { get; set; }
        public Nullable<decimal> FloorCostSavings { get; set; }
        public string InvoiceTerms { get; set; }
        public string DeliveryTerms { get; set; }
        public string LocalBankAccountNo { get; set; }
        public string DollarBankAccountNo { get; set; }
        public string QuotationTemporaryMessage { get; set; }
        public string POTemporaryMessage { get; set; }
        public string InvoiceTemporaryMessage { get; set; }
        public Nullable<int> TenantId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public int CompanyId { get; set; }
        public int LocationId { get; set; }
        public int Createdby { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Deletedby { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
