//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sperience
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerAddresses = new HashSet<CustomerAddress>();
            this.CustomerClassifications = new HashSet<CustomerClassification>();
            this.CustomerContacts = new HashSet<CustomerContact>();
            this.CustomerCreditLines = new HashSet<CustomerCreditLine>();
        }
    
        public int Id { get; set; }
        public string RegistrationId { get; set; }
        public string GSTRegistrationId { get; set; }
        public string Domain { get; set; }
        public string CustomerName { get; set; }
        public string CustomerDescription { get; set; }
        public Nullable<int> PaymentTermId { get; set; }
        public int IndustryId { get; set; }
        public int CustomerTypeId { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string SocialMediaAcct1 { get; set; }
        public string SocialMediaAcct2 { get; set; }
        public string SocialMediaAcct3 { get; set; }
        public string SocialMediaAcct4 { get; set; }
        public string ManagingMembers { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ContextCompanyId { get; set; }
        public Nullable<int> ContextLocationId { get; set; }
        public Nullable<int> ParentCustomerId { get; set; }
        public bool Active { get; set; }
        public int CompanyId { get; set; }
        public int LocationId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Createdby { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> Deletedby { get; set; }
        public string TempERPId { get; set; }
    
        public virtual ICollection<CustomerAddress> CustomerAddresses { get; set; }
        public virtual ICollection<CustomerClassification> CustomerClassifications { get; set; }
        public virtual ICollection<CustomerContact> CustomerContacts { get; set; }
        public virtual ICollection<CustomerCreditLine> CustomerCreditLines { get; set; }
    }
}
