//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sperience
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectAction
    {
        public SubjectAction()
        {
            this.SubjectActionChecklists = new HashSet<SubjectActionChecklist>();
            this.SubjectActionExpenses = new HashSet<SubjectActionExpense>();
        }
    
        public int Id { get; set; }
        public int SubjectId { get; set; }
        public int ActionId { get; set; }
        public int ActionTypeId { get; set; }
        public int StageActionId { get; set; }
        public string ActionTitle { get; set; }
        public string ActionDescription { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public Nullable<int> OutcomeId { get; set; }
        public string OutcomeDescription { get; set; }
        public int Assignedto { get; set; }
        public int CompanyId { get; set; }
        public int LocationId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Createdby { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> Deletedby { get; set; }
    
        public virtual SubjectHeader SubjectHeader { get; set; }
        public virtual ICollection<SubjectActionChecklist> SubjectActionChecklists { get; set; }
        public virtual ICollection<SubjectActionExpense> SubjectActionExpenses { get; set; }
    }
}
