//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sperience
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectHeader
    {
        public SubjectHeader()
        {
            this.SubjectActions = new HashSet<SubjectAction>();
            this.SubjectCategories = new HashSet<SubjectCategory>();
            this.SubjectDocuments = new HashSet<SubjectDocument>();
            this.SubjectMarketChannels = new HashSet<SubjectMarketChannel>();
            this.SubjectNotes = new HashSet<SubjectNote>();
            this.SubjectRatings = new HashSet<SubjectRating>();
        }
    
        public int Id { get; set; }
        public int StageId { get; set; }
        public string SubjectId { get; set; }
        public int SubjectTypeId { get; set; }
        public string SubjectTitle { get; set; }
        public string SubjectDescription { get; set; }
        public System.DateTime SubjectDate { get; set; }
        public System.DateTime ClosingDate { get; set; }
        public int ClosingDateTypeId { get; set; }
        public Nullable<int> BudgetaryAllocationId { get; set; }
        public int CurrencyId { get; set; }
        public Nullable<decimal> RevenueEstimate { get; set; }
        public int ClassificationId { get; set; }
        public int AccountId { get; set; }
        public int AccountContactId { get; set; }
        public int SubjectManagerId { get; set; }
        public int CompanyId { get; set; }
        public int LocationId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Createdby { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> Deletedby { get; set; }
    
        public virtual Stage Stage { get; set; }
        public virtual ICollection<SubjectAction> SubjectActions { get; set; }
        public virtual ICollection<SubjectCategory> SubjectCategories { get; set; }
        public virtual ICollection<SubjectDocument> SubjectDocuments { get; set; }
        public virtual ICollection<SubjectMarketChannel> SubjectMarketChannels { get; set; }
        public virtual ICollection<SubjectNote> SubjectNotes { get; set; }
        public virtual ICollection<SubjectRating> SubjectRatings { get; set; }
    }
}
