//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sperience
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeDimension
    {
        public int Id { get; set; }
        public int DateKey { get; set; }
        public string Day { get; set; }
        public string Month { get; set; }
        public Nullable<int> MonthNumber { get; set; }
        public string Quarter { get; set; }
        public int Year { get; set; }
        public System.DateTime CDate { get; set; }
    }
}
