//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sperience
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string Fullname { get; set; }
        public int DepartmentId { get; set; }
        public Nullable<int> ReportingOfficerId { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<System.DateTime> ResignationDate { get; set; }
        public string DID { get; set; }
        public string Team { get; set; }
        public bool Active { get; set; }
        public bool AllowCrossDomain { get; set; }
        public Nullable<int> DeputyId { get; set; }
        public int ContextCompanyId { get; set; }
        public int ContextLocationId { get; set; }
        public int CompanyId { get; set; }
        public int LocationId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Createdby { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> Deletedby { get; set; }
    }
}
